databases:
  - name: coopcredit-db
    databaseName: coopcredit_db
    user: coopcredit_user
    plan: free

services:
  # 1. Risk Central Mock Service
  - type: web
    name: risk-central-mock-service
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./risk-central-mock-service
    envVars:
      - key: PORT
        value: 8081
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health

  # 2. Creddit Application Service
  - type: web
    name: creddit-application-service
    runtime: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: ./creddit-application-service
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_USERNAME
        fromDatabase:
          name: coopcredit-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: coopcredit-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: coopcredit-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: coopcredit-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: coopcredit-db
          property: databaseName
      - key: RISK_CENTRAL_URL
        fromService:
          type: web
          name: risk-central-mock-service
          envVarKey: RENDER_EXTERNAL_URL
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /actuator/health
